Matrix and operation

In [ ]:
install.packages("matrixcalc")
library(matrixcalc)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



corr
cov
dis
xxt
xtx
orthogonal
orthonormal
eigen vector
dia
symm


**Identity matrix**

An identity matrix is a given square matrix of any order which contains on its main diagonal elements with value of one, while the rest of the matrix elements are equal to zero.

In [ ]:
#identity matrix of order 3 by 3
identity3by3 = matrix(c(1,0,0,0,1,0,0,0,1),byrow = TRUE, nrow = 3)
print(identity3by3)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


**Zero or Null Matrix**

If all the elements are zero in a matrix, then it is called a zero matrix and generally denoted by 0. Thus, A = [aij]mxn is a zero-matrix if aij = 0 for all i and j; E.g.
\begin{array}{l}\left[ \begin{matrix} 0 & 0 & 0 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \\ \end{matrix} \right]\end{array}

In [ ]:
zero_mat = matrix(0,2,3)
print(zero_mat)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0


**Diagonal Matrix**

If all the elements, except the principal diagonal, in a square matrix, are zero, it is called a diagonal matrix. Thus, a square matrix A = [aij] is a diagonal matrix if aij = 0,when i ≠ j.
\begin{array}{l}E.g.\left[ \begin{matrix} 2 & 0 & 0 \\ 0 & 3 & 0 \\ 0 & 0 & 4 \\ \end{matrix} \right]\end{array}

In [ ]:
dia_mat = diag(2:4,3,3)
print(dia_mat)

     [,1] [,2] [,3]
[1,]    2    0    0
[2,]    0    3    0
[3,]    0    0    4


In [ ]:
#using diag function
identity = diag(3)
print(identity)

     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1


**Transpose**

The transpose of a matrix is found by interchanging its rows into columns or columns into rows.

In [ ]:
mat = matrix(1:12,byrow = TRUE, nrow = 3,dimnames = list(c('A','B','C'),c('col1','col2','col3','col4')))
print(mat)
print("After transpose")
print(t(mat))

  col1 col2 col3 col4
A    1    2    3    4
B    5    6    7    8
C    9   10   11   12
[1] "After transpose"
     A B  C
col1 1 5  9
col2 2 6 10
col3 3 7 11
col4 4 8 12


**Addition**

If A[aij]mxn and B[bij]mxn are two matrices of the same order, then their sum A + B is a matrix, and each element of that matrix is the sum of the corresponding elements, i.e. A + B = [aij + bij]mxn

In [ ]:
matrix1 = matrix(c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

matrix2 = matrix(c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4


In [ ]:
#adding two matrices
adding_mat = matrix1 + matrix2
print(adding_mat)

     [,1] [,2] [,3]
[1,]    8   -1    5
[2,]   11   13   10


**Subtraction**

If A and B are two matrices of the same order, then we define A - B = A + (-B)

In [ ]:
#subtracting
sub_mat = matrix1 - matrix2
print(sub_mat)

     [,1] [,2] [,3]
[1,]   -2   -1   -1
[2,]    7   -5    2


**Multiplication**

If A and B be any two matrices, then their product AB will be defined only when the number of columns in A is equal to the number of rows in B.

\begin{array}{l}A={{\left[ {{a}_{ij}} \right]}_{m\,\times n}}. and \,B={{\left[ {{b}_{ij}} \right]}_{n\,\times p}} then\; their\; product\ AB=C={{\left[ {{c}_{ij}} \right]}_{m\,\times p}}\end{array}
will be a matrix of order m×p where
\begin{array}{l}{{\left( AB \right)}_{ij}}={{C}_{ij}}=\sum\limits_{r=1}^{n}{{{a}_{ir}}{{b}_{rj}}}\end{array}

In [ ]:
#multiplying
A = matrix1%*%t(matrix2)
B = t(matrix1)%*%matrix2
print("Creating 2 by 2 matrix")
print(A)
print("Creating 3 by 3 matrix")
print(B)

[1] "Creating 2 by 2 matrix"
     [,1] [,2]
[1,]   21    5
[2,]   63   78
[1] "Creating 3 by 3 matrix"
     [,1] [,2] [,3]
[1,]   33   81   45
[2,]    3   36   13
[3,]   22   54   30


**Scalar multiplication**

If A = [aij]m×n is a matrix and k any number, then the matrix which is obtained by multiplying the elements of A by k is called the scalar multiplication of A by k, and it is denoted by k A, thus if A = [aij]m×n,

Then,
\begin{array}{l}k{{A}_{m\,\times n}}={{A}_{m\,\times \,n}}k=\left[ k{{a}_{i\times j}} \right]\end{array}



In [ ]:
scalar_mat1 = 5*matrix1
scalar_mat2 = matrix1*5
print(scalar_mat1)
print(scalar_mat2)
print(scalar_mat1 == scalar_mat2)

     [,1] [,2] [,3]
[1,]   15   -5   10
[2,]   45   20   30
     [,1] [,2] [,3]
[1,]   15   -5   10
[2,]   45   20   30
     [,1] [,2] [,3]
[1,] TRUE TRUE TRUE
[2,] TRUE TRUE TRUE


**Symmetric and Skew Symmetric Matrices**

**Symmetric matrix:** A square matrix A = [aij] is called a symmetric matrix if aij = aji, for all i,j values;
Eg:
\begin{array}{l}A=\left( \begin{matrix} 1 & 2 & 3 \\ 2 & 4 & 5 \\ 3 & 5 & 2 \\ \end{matrix} \right)\end{array}
is symmetric, because a12 = 2 = a21, a31 = 3 = a13 etc.

Note: A is symmetric if A’ = A (where ‘A’ is the transpose of the matrix)

**Skew-Symmetric Matrix:** A square matrix A = [aij] is a skew-symmetric matrix if aij = aji, for all values of i,j.
[putting j = i] aii = 0
Thus, in a skew-symmetric matrix, all diagonal elements are zero; E.g.
\begin{array}{l}A=\left[ \begin{matrix} 0 & 2 & 1 \\ -2 & 0 & -3 \\ -1 & 3 & 0 \\ \end{matrix} \right],B=\left[ \begin{matrix} 0 & 2 \\ -2 & 0 \\ \end{matrix} \right]\end{array}
are skew-symmetric matrices.

Note: A square matrix A is a skew-symmetric matrix A’ = -A.

In [ ]:
my_mat = matrix(c(1, 2, 3, 4,
                   0, 1, 5, 6,
                   0, 0, 1, 7,
                   0, 0, 0, 1),
                 ncol = 4)

my_sym = my_mat
my_sym[upper.tri(my_sym)] = t(my_sym)[upper.tri(my_sym)]
print(my_sym)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    2    1    5    6
[3,]    3    5    1    7
[4,]    4    6    7    1


In [ ]:
#Checking  A’ = A
z <- my_sym == t(my_sym)
print(z)

     [,1] [,2] [,3] [,4]
[1,] TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE
[4,] TRUE TRUE TRUE TRUE


In [ ]:
#Checking using is_symmetric_matrix() function
isSymmetric(my_sym)

[1] TRUE

In [ ]:
x = matrix(1:4,nrow = 2)
print(x)
print(isSymmetric(x))

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[1] FALSE


In [ ]:
my_skew = 0.5*(my_mat - t(my_mat))
print(my_skew)

     [,1] [,2] [,3] [,4]
[1,]  0.0 -1.0 -1.5 -2.0
[2,]  1.0  0.0 -2.5 -3.0
[3,]  1.5  2.5  0.0 -3.5
[4,]  2.0  3.0  3.5  0.0


In [ ]:
#checking skew_symm
print(my_skew == -t(my_skew))


     [,1] [,2] [,3] [,4]
[1,] TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE
[3,] TRUE TRUE TRUE TRUE
[4,] TRUE TRUE TRUE TRUE


In [ ]:
x = matrix(1:4,nrow = 2)
print(x)
print(is.skew.symmetric.matrix(x))

     [,1] [,2]
[1,]    1    3
[2,]    2    4
[1] FALSE


**Determinant of Matrix**

The determinant of a matrix is the scalar value or number calculated using a square matrix. The square matrix could be 2×2, 3×3, 4×4, or any type, such as n × n, where the number of column and rows are equal. If S is the set of square matrices, R is the set of numbers (real or complex) and f : S → R is defined by f (A) = k, where A ∈ S and k ∈ R, then f (A) is called the determinant of A.
The value of the determinant of a 2 × 2 matrix can be given as

det A =
\begin{array}{l} a_{11} × a_{22} – a_{21} × a_{21} \end{array}

**Adjoint of a Matrix**

The transpose of the matrix of co-factors is called the adjoint of matrix A and is written as adj A. \begin{array}{l}If A=\left[ \begin{matrix} {{a}_{11}} & {{a}_{12}} & {{a}_{13}} \\ {{a}_{21}} & {{a}_{22}} & {{a}_{23}} \\ {{a}_{31}} & {{a}_{32}} & {{a}_{33}} \\ \end{matrix} \right]\end{array}

The matrix formed by the cofactors of the elements is
\begin{array}{l}\left[ \begin{matrix} {{A}_{11}} & {{A}_{12}} & {{A}_{13}} \\ {{A}_{21}} & {{A}_{22}} & {{A}_{23}} \\ {{A}_{31}} & {{A}_{32}} & {{A}_{33}} \\ \end{matrix} \right]\end{array}
Therefore,
\begin{array}{l}adj\,A=\left[ \begin{matrix} {{A}_{11}} & {{A}_{21}} & {{A}_{31}} \\ {{A}_{12}} & {{A}_{22}} & {{A}_{32}} \\ {{A}_{13}} & {{A}_{23}} & {{A}_{33}} \\ \end{matrix} \right]\end{array}
**Inverse of a Matrix**

If A and B are two square matrices of the same order, such that AB = BA = I (I = unit matrix), then B is called the inverse of A, i.e., B = A–1, and A is the inverse of B. Condition for a square matrix A to possess an inverse is that the matrix A is non-singular, i.e., | A | ≠ 0. If A is a square matrix and B is its inverse, then AB = I. Taking the determinant of both sides | AB | = | I | or | A | | B | = I. From this relation, it is clear that | A | ≠ 0, i.e. the matrix A is non-singular.
\begin{array}{l}{{A}^{-1}}=\frac{1}{\left| A \right|}\left( Adj.\,A \right)\end{array}

In [ ]:
M = matrix(c( 0, 3, 1, -2, 1, 4, -1,- 4, 0 ),nrow = 3,byrow = TRUE)
print(M)
#calculate the det
det_M = det(M)
# Calculate the inverse of the matrix
inv_M = matrix.inverse(M)
# Calculate the adjoint of the matrix
adj_M = det_M * inv_M
# Print the adjoint matrix
print("Adjoint")
print(adj_M)
print("detreminant")
print(det_M)
print("inverse")
print(inv_M)

     [,1] [,2] [,3]
[1,]    0    3    1
[2,]   -2    1    4
[3,]   -1   -4    0
[1] "Adjoint"
     [,1] [,2] [,3]
[1,]   16   -4   11
[2,]   -4    1   -2
[3,]    9   -3    6
[1] "detreminant"
[1] -3
[1] "inverse"
          [,1]       [,2]       [,3]
[1,] -5.333333  1.3333333 -3.6666667
[2,]  1.333333 -0.3333333  0.6666667
[3,] -3.000000  1.0000000 -2.0000000


**Rank of a Matrix**

The maximum number of linearly independent columns (or rows) of a matrix is called the rank of a matrix. The rank of a matrix cannot exceed the number of its rows or columns.
If we consider a square matrix, the columns (rows) are linearly independent only if the matrix is nonsingular. In other words, the rank of any nonsingular matrix of order m is m. The rank of a matrix A is denoted by ρ(A).

The rank of a null matrix is zero. A null matrix has no non-zero rows or columns. So, there are no independent rows or columns. Hence, the rank of a null matrix is zero.

In [ ]:
print(my_sym)
print("Rank of this matrix is")
print(qr(my_sym)$rank)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    2    1    5    6
[3,]    3    5    1    7
[4,]    4    6    7    1
[1] "Rank of this matrix is"
[1] 4


In [ ]:
zero = matrix(0,3,3)
print(zero)
print("Rank of this matrix is")
print(qr(zero)$rank)

     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0
[1] "Rank of this matrix is"
[1] 0


The dimensions of a matrix are the number of rows by the number of columns.

In [ ]:
print(dim(my_skew))

[1] 4 4


Practical uses:

**Row Sum and Column Sum:**
- **Data Analysis:** In data analysis, the sum of rows or columns in a matrix (which might represent a data set) can be useful for comparative analysis tools such as analysis of variance, chi−square testing.
- **Image Processing:** In image processing, the sum of rows or columns can be used to analyze the distribution of pixel values.
- **Graph Theory:** In graph theory, the sum of rows or columns in an adjacency matrix represents the degree of each vertex in the graph.
- **Statistics:** In statistics, the sum of rows or columns in a contingency table is used in chi-square tests for independence.

**Trace of a Matrix:**
- **Eigenvalues:** The trace of a matrix is the sum of its eigenvalues. This property can be exploited for proving certain results.
- **Invariant Property:** The trace of a matrix is an invariant under changes of basis and therefore remains the same under different perspectives.
- **Linear Algebra:** In linear algebra, the trace of a matrix is used in the characterization of several matrix norms.
- **Differential Geometry:** In differential geometry, if the matrix is a curvature tensor, the trace gives the mean curvature.

Remember, these operations are defined for square matrices. For non-square matrices, you might need to adjust your approach accordingly.


In [ ]:
print(my_mat)
print("Row sum of this matrix is")
print(rowSums(my_mat))

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    2    1    0    0
[3,]    3    5    1    0
[4,]    4    6    7    1
[1] "Row sum of this matrix is"
[1]  1  3  9 18


In [ ]:
print(my_mat)
print("Column sum of this matrix is")
print(colSums(my_mat))

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    2    1    0    0
[3,]    3    5    1    0
[4,]    4    6    7    1
[1] "Column sum of this matrix is"
[1] 10 12  8  1


In [ ]:
print(my_mat)
print("Trace of this matrix is")
print(matrix.trace(my_mat))

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    0
[2,]    2    1    0    0
[3,]    3    5    1    0
[4,]    4    6    7    1
[1] "Trace of this matrix is"
[1] 4


**Eigenvalue Definition**

Eigenvalues are the special set of scalars associated with the system of linear equations. It is mostly used in matrix equations. ‘Eigen’ is a German word that means ‘proper’ or ‘characteristic’. Therefore, the term eigenvalue can be termed as characteristic value, characteristic root, proper values or latent roots as well. In simple words, the eigenvalue is a scalar that is used to transform the eigenvector. The basic equation is

                                    Ax = λx

The number or scalar value “λ” is an eigenvalue of A

**EigenVectors**
Eigenvectors are the vectors (non-zero) that do not change the direction when any linear transformation is applied. It changes by only a scalar factor. In a brief, we can say, if A is a linear transformation from a vector space V and x is a vector in V, which is not a zero vector, then v is an eigenvector of A if A(X) is a scalar multiple of x.

Eigenvalues and eigenvectors have a wide range of practical applications in various fields. Here are some examples:

1. **System of Communication:** Claude Shannon used eigenvalues to calculate the theoretical limit of how much information can be carried via a communication channel such as a telephone line or the air.
2. **Bridge Construction:** The smallest magnitude eigenvalue of a system that models the bridge is the natural frequency of the bridge. Engineers use this knowledge to ensure that their structures are stable.
3. **Automobile Stereo System Design:** Eigenvalue analysis is also used in the design of car stereo systems, where it aids in the reproduction of car vibration caused by music.
4. **Electrical Engineering:** The use of eigenvalues and eigenvectors to decouple three-phase systems via symmetrical component transformation is advantageous.
5. **Mechanical Engineering:** Eigenvalues and eigenvectors enable us to "decompose" a linear process into smaller, more manageable tasks. For example, when stress is applied to a "plastic" solid, the deformation can be divided into "principle directions," or the directions where the deformation is greatest.
6. **Image Compression:** Using singular value decomposition for image compression. You can compress an image by throwing away the small eigenvalues.
7. **Special Relativity:** Deriving Special Relativity is more natural in the language of linear algebra. In fact, Einstein's second postulate really states that "Light is an eigenvector of the Lorentz transform.
8. **Spectral Clustering:** Whether it's in plants and biology, medical imaging, business and marketing, understanding the connections between fields on Facebook, or even criminology, clustering is an extremely important part of modern data analysis.



In [ ]:
A = matrix(c(13, -4, 2, -4, 11, -2, 2, -2, 8), 3, 3, byrow=TRUE)
print(A)
Ei = eigen(A)
vec = Ei$values
print("Eigen values are")
print(vec)
print("Eigen vectors are")
print(Ei$vectors)


     [,1] [,2] [,3]
[1,]   13   -4    2
[2,]   -4   11   -2
[3,]    2   -2    8
[1] "Eigen values are"
[1] 17  8  7
[1] "Eigen vectors are"
           [,1]       [,2]      [,3]
[1,]  0.7453560  0.6666667 0.0000000
[2,] -0.5962848  0.6666667 0.4472136
[3,]  0.2981424 -0.3333333 0.8944272


**Orthogonal Matrix:** A square matrix `A` is orthogonal if `A^T = A^-1` or `A^T * A = I`, where `A^T` is the transpose of `A`, `A^-1` is the inverse of `A`, and `I` is the identity matrix. They are used in signal processing, time series analysis, linear algebra algorithms, and QR decomposition.

**Orthonormal Matrix:** A matrix is orthonormal if it's orthogonal and all its vectors have a magnitude of 1. They are used in eigenvalue decomposition, spectral decomposition, Principal Component Analysis (PCA), etc.

In [4]:
#update
